--****************************************************
-- Bases de datos: Introducción a SQL
-- Autor: Douglas Hernández
-- Correspondencia: dohernandez@uca.edu.sv
-- Version: 1.0
--****************************************************

-- 01.00    QUERIES PLANAS
-- 01.01    MOSTRAR TODAS LAS RESERVAS

SELECT * 
FROM RESERVA;

-- 01.02    MOSTRAR LOS CAMPOS checkin, checkout, id_cliente_reserva, id_habitacion

SELECT checkin, checkout, id_cliente_reserva, id_habitacion 
FROM RESERVA;

-- 01.03    MOSTRAR LOS MISMOS CAMPOS PERO CON OTROS IDENTIFICADORES

SELECT checkin as 'Fecha de entrada', 
    checkout as 'Fecha de salida', 
    id_cliente_reserva 'Cliente que Reserva', 
    id_habitacion 'Habitación'
FROM RESERVA;

-- ************************************************************************************************ --

-- 02.00    CONDICIONES EN QUERIES
-- 02.01    MOSTRAR TODAS LAS RESERVAS CON id MAYOR A 90

SELECT * 
FROM RESERVA
WHERE id > 80;

-- 02.02    AND: MOSTRAR TODAS LAS RESERVAS CON ID ENTRE 25 Y 40

SELECT *
FROM RESERVA
WHERE id >= 25 AND id <= 40;

-- 02.03    BETWEEN: MOSTRAR TODAS LAS RESERVAS CON id ENTRE 25 Y 40

SELECT *
FROM RESERVA
WHERE id BETWEEN 25 AND 40;

-- 02.04    NOT: MOSTRAR TODAS LAS RESERVAS CON id FUERA DEL RANGO 25 - 40

SELECT *
FROM RESERVA
WHERE id NOT BETWEEN 25 AND 40;

SELECT * 
FROM RESERVA
WHERE NOT id > 80;

SELECT * 
FROM RESERVA
WHERE id <> 10;

-- 02.05    OR: MOSTRAR TODAS LAS RESERVAS CON id ENTRE ESTOS RANGOS [10-15] | [30-40]

SELECT *
FROM RESERVA
WHERE (id BETWEEN 10 AND 15) OR (id BETWEEN 30 AND 40);

-- 02.06    ¿Y SI LO CAMBIAMOS POR AND? NO TENDRIA SENTIDO

SELECT *
FROM RESERVA
WHERE (id BETWEEN 10 AND 15) AND (id BETWEEN 30 AND 40);

-- 02.07    COMBINADO CONDICIONES: MOSTRAR LAS RESERVAS CON id MENORES A 10, MAYORES A 90, Y MENORES A 100

SELECT * 
FROM RESERVA
WHERE (id < 10 OR id > 90) AND id <100; -- ESTE NO INCLUYE 90 y 100

SELECT * 
FROM RESERVA
WHERE id < 10 OR id BETWEEN 90 AND 100; -- ESTE INCLUYE 90 y 100

-- 02.08    MANEJO DE DATE: MOSTRAR LAS RESERVAS PLANIFICADAS PARA MAYO

SELECT * 
FROM RESERVA
WHERE checkin >= '2022-05-01' AND checkin <= '2022-05-31';

-- 02.09    DATE&BETWEEN: MOSTRAR LAS RESERVAS PLANIFICADAS PARA MAYO

SELECT * 
FROM RESERVA
WHERE checkin BETWEEN '2022-05-01' AND '2022-05-31';

-- 02.10    FUNCION MONTH: MOSTRAR LAS RESERVAS PLANIFICADAS PARA MAYO

SELECT * 
FROM RESERVA
WHERE MONTH(checkin) = 5;

-- 02.11    FUNCION YEAR: MOSTRAR LAS RESERVAS PLANIFICADAS PARA MAYO DE 2022

SELECT * 
FROM RESERVA
WHERE MONTH(checkin) = 5 AND YEAR(checkin) = 2022;

-- 02.12    FUNCION DAY: MOSTRAR LAS RESERVAS PLANIFICADAS PARA DESPUES DEL 10 DE MAYO

SELECT *
FROM RESERVA
WHERE MONTH(checkin) = 5 AND DAY(checkin) > 10;

-- 02.13    FUNCION DATEDIFF: MOSTRAR TODAS LAS RESERVAS CON ESTANCIA MAYOR A 3 DIAS

SELECT *
FROM RESERVA 
WHERE DATEDIFF(DAY, checkin, checkout) > 3;

-- 02.14    LIMPIANDO LA SALIDA DE LA EJECUCIÓN 02.13

SELECT checkin, checkout, DATEDIFF(DAY, checkin, checkout) as "Estancia"
FROM RESERVA 
WHERE DATEDIFF(DAY, checkin, checkout) > 3;

-- 02.15    LIKE 01: MOSTRAR LOS CORREOS QUE FINALICEN EN ".edu"

SELECT * 
FROM CORREO_CLIENTE
WHERE correo LIKE '%@%.edu';

-- 02.16    LIKE 02: MOSTRAR LOS CORREOS QUE SE ENCUENTREN EN EL DOMINIO "outlook"

SELECT * 
FROM CORREO_CLIENTE
WHERE correo LIKE '%@%outlook.%';


-- 02.18    LIKE 03: MOSTRAR LOS CORREOS QUE NO SE ENCUENTREN EN EL DOMINIO "outlook"

SELECT * 
FROM CORREO_CLIENTE
WHERE correo NOT LIKE '%@%outlook.%';

-- 02.17    LIKE 04: MOSTRAR LOS CORREOS QUE TENGAN UN PUNTO EN SU NOMBRE (.)

SELECT * 
FROM CORREO_CLIENTE
WHERE correo LIKE '%.%@%';

-- 03.00    AGRUPAMIENTO DE TABLAS
-- 03.00    CONSULTANDO EL CLIENTE CON id = 1 Y EL CORREO CON id_cliente = 1

SELECT *
FROM CLIENTE
WHERE id = 1;

SELECT *
FROM CORREO_CLIENTE
WHERE id_cliente = 1;

-- 03.01    MOSTRAR TODOS LOS CORREOS CON EL NOMBRE DEL CLIENTE ASIGNADO

SELECT *
FROM CLIENTE, CORREO_CLIENTE
WHERE CLIENTE.id = CORREO_CLIENTE.id_cliente;

SELECT CORREO_CLIENTE.correo, CLIENTE.nombre, CLIENTE.documento
FROM CLIENTE, CORREO_CLIENTE
WHERE CLIENTE.id = CORREO_CLIENTE.id_cliente;

-- 03.02    MOSTRAR DE CADA HOTEL EL id, nombre, telefono, Y NOMBRE DE LA CATEGORIA A LA QUE PERTENCE

SELECT H.id, H.nombre, H.telefono, Cat.categoria
FROM HOTEL H, CATEGORIA_HOTEL Cat
WHERE H.id_categoria_hotel = Cat.id;

-- 03.03    MOSTRAR TODA LA INFORMACIÓN DE CLIENTE INLUYENDO EL PAIS DE ORIGEN Y LA CATEGORIA A LA QUE PERTENECE

SELECT C.documento, C.nombre, CC.categoria, P.pais
FROM CLIENTE C, CATEGORIA_CLIENTE CC, PAIS P
WHERE C.id_pais = P.id AND C.categoria_cliente = CC.id;

-- 03.03    MOSTRAR TODA LA INFORMACIÓN DE CLIENTE INLUYENDO EL PAIS DE ORIGEN DE AQUELLOS CUYA CATEGORIA SEA "backpacker"

SELECT C.documento, C.nombre, CC.categoria, P.pais
FROM CLIENTE C, CATEGORIA_CLIENTE CC, PAIS P
WHERE 
    C.id_pais = P.id 
    AND C.categoria_cliente = CC.id
    AND CC.categoria = 'backpacker';

-- 03.03    MOSTRAR TODA LA INFORMACIÓN DE CLIENTE INLUYENDO EL PAIS DE ORIGEN DE AQUELLOS CUYA CATEGORIA SEA "backpacker" USANDO EL ID DE CATEGORIA

SELECT C.documento, C.nombre, CC.categoria, P.pais
FROM CLIENTE C, CATEGORIA_CLIENTE CC, PAIS P
WHERE 
    C.id_pais = P.id 
    AND C.categoria_cliente = CC.id
    AND CC.id = 1;

-- 03.04    MOSTRAR TODA LA INFORMACIÓN DE CLIENTE INLUYENDO EL PAIS DE ORIGEN Y CATEGORIA DE AQUELLOS CUYO ORIGEN SEA CENTROAMERICANO



-- 03.04    MOSTRAR TODA LA INFORMACIÓN DE CLIENTE INLUYENDO EL PAIS DE ORIGEN Y CATEGORIA DE AQUELLOS CUYO ORIGEN SEA CENTROAMERICANO USANDO LAS PK DE PAIS



-- 03.04    IN: MOSTRAR TODA LA INFORMACIÓN DE CLIENTE INLUYENDO EL PAIS DE ORIGEN Y CATEGORIA DE AQUELLOS CUYO ORIGEN SEA CENTROAMERICANO USANDO LAS PK DE PAIS


SELECT C.documento, C.nombre, CC.categoria, P.pais
FROM CLIENTE C, CATEGORIA_CLIENTE CC, PAIS P
WHERE 
    C.id_pais = P.id 
    AND C.categoria_cliente = CC.id
    AND P.pais IN ('El Salvador', 'Guatemala', 'Honduras', 'Costa Rica', 'Nicaragua');

SELECT C.documento, C.nombre, CC.categoria, P.pais
FROM CLIENTE C, CATEGORIA_CLIENTE CC, PAIS P
WHERE 
    C.id_pais = P.id 
    AND C.categoria_cliente = CC.id
    AND P.id IN (1, 2, 3, 4, 5);